# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62df22f94997ebfc00d685777abc328bfd2a11828df1eb4f64ccda0bd6e903d92e93780b4a52e45144ba9d79528fb38236d7524bd7131f64943f105cc2b163e3

test:
  secret_key_base: cc5e13e4f56ad78fd9bb2229014637fddb4cdb71bda7be9b9fd0fd0c92a3c5572afc41af7d0fb1e54881e46416f30f4386ec3a035f7f06337a92746e56451860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
